/*
 * Copyright 2017 Jean-Paul Calbimonte
 *
 * SPDX-License-Identifier: MIT
 */

package rdftools.rdf.vocab

import rdftools.rdf.Vocab

import rdftools.rdf._

import rdftools.rdf.RdfTools._

object DCterms extends Vocab {
  override val iri: Iri = "http://purl.org/dc/terms/"
  val LicenseDocument = clazz("LicenseDocument")
  val PhysicalMedium = clazz("PhysicalMedium")
  val Policy = clazz("Policy")
  val LocationPeriodOrJurisdiction = clazz("LocationPeriodOrJurisdiction")
  val PeriodOfTime = clazz("PeriodOfTime")
  val Standard = clazz("Standard")
  val Frequency = clazz("Frequency")
  val ProvenanceStatement = clazz("ProvenanceStatement")
  val MediaType = clazz("MediaType")
  val PhysicalResource = clazz("PhysicalResource")
  val MediaTypeOrExtent = clazz("MediaTypeOrExtent")
  val FileFormat = clazz("FileFormat")
  val Location = clazz("Location")
  val MethodOfInstruction = clazz("MethodOfInstruction")
  val BibliographicResource = clazz("BibliographicResource")
  val Jurisdiction = clazz("Jurisdiction")
  val MethodOfAccrual = clazz("MethodOfAccrual")
  val AgentClass = clazz("AgentClass")
  val RightsStatement = clazz("RightsStatement")
  val SizeOrDuration = clazz("SizeOrDuration")
  val Agent = clazz("Agent")
  val LinguisticSystem = clazz("LinguisticSystem")
  val hasFormat = prop("hasFormat")
  val source = prop("source")
  val isVersionOf = prop("isVersionOf")
  val isReplacedBy = prop("isReplacedBy")
  val created = prop("created")
  val relation = prop("relation")
  val conformsTo = prop("conformsTo")
  val isReferencedBy = prop("isReferencedBy")
  val rights = prop("rights")
  val provenance = prop("provenance")
  val dateAccepted = prop("dateAccepted")
  val title = prop("title")
  val accessRights = prop("accessRights")
  val description = prop("description")
  val `abstract` = prop("abstract")
  val accrualPolicy = prop("accrualPolicy")
  val medium = prop("medium")
  val replaces = prop("replaces")
  val creator = prop("creator")
  val temporal = prop("temporal")
  val bibliographicCitation = prop("bibliographicCitation")
  val rightsHolder = prop("rightsHolder")
  val issued = prop("issued")
  val alternative = prop("alternative")
  val requires = prop("requires")
  val extent = prop("extent")
  val accrualMethod = prop("accrualMethod")
  val dateSubmitted = prop("dateSubmitted")
  val instructionalMethod = prop("instructionalMethod")
  val `type` = prop("type")
  val date = prop("date")
  val contributor = prop("contributor")
  val hasPart = prop("hasPart")
  val language = prop("language")
  val coverage = prop("coverage")
  val identifier = prop("identifier")
  val tableOfContents = prop("tableOfContents")
  val valid = prop("valid")
  val educationLevel = prop("educationLevel")
  val references = prop("references")
  val isFormatOf = prop("isFormatOf")
  val subject = prop("subject")
  val dateCopyrighted = prop("dateCopyrighted")
  val mediator = prop("mediator")
  val hasVersion = prop("hasVersion")
  val format = prop("format")
  val isPartOf = prop("isPartOf")
  val accrualPeriodicity = prop("accrualPeriodicity")
  val publisher = prop("publisher")
  val isRequiredBy = prop("isRequiredBy")
  val license = prop("license")
  val available = prop("available")
  val spatial = prop("spatial")
  val audience = prop("audience")
  val modified = prop("modified")
}